### PR TITLE
Use CMake variable for lib prefix instead of hard-coding

### PR DESCRIPTION
**Pull request by EricHripko**
# Overview
This PR substitutes hard-coded `lib` prefix with `${CMAKE_STATIC_LIBRARY_PREFIX}`, which enables bde-tools to work on non-Unix platforms. The minimum example to reproduce the issue can be seen in [EricHripko/bde-tools-b01](https://github.com/EricHripko/bde-tools-b01) repo. This is a safe change, because:
- Behaviour on *nix remains the same (the variable contains `lib` value)
- Minimum required version for CMake is unaffected by it

# Testing
Before/after versions were built and tested on Linux and Windows.
## Linux
Behaviour is correct and unchanged.
```
$ cmake ....
-- Configuring done
-- Generating done
...
-- Resolving EXTERNAL dependencies: bsl.
-- =========================================
-- =====            SUMMARY            =====
-- =========================================
--  RefRoot..........: ~/vcpkg/installed/x64-linux
--  BuildType........: Debug
--  UFID.............: 64_dbg
--  Canonical UFID...: dbg_64
--  Install UFID.....: dbg_64
--  Install lib path.: lib64
-- =========================================
-- Configuring done
-- Generating done

$ make test
Running tests...
Test project /mnt/c/Workspaces/bde-tools-windows/build
    Start 1: mylibrary_hello.t
1/1 Test #1: mylibrary_hello.t ................   Passed    0.91 sec

100% tests passed, 0 tests failed out of 1

Label Time Summary:
mylibrary            =   0.91 sec*proc (1 test)
mylibrary_hello      =   0.91 sec*proc (1 test)
mylibrary_hello.t    =   0.91 sec*proc (1 test)

Total Test time (real) =   0.93 sec
```
## Windows
Before the fix, resolution of dependencies would fail and cause CMake to fail overall:
```
$ cmake ....
CMake Error: install(EXPORT "mylibraryInterfaceTargets" ...) includes target "mylibrary-uor-INTERFACE" which requires target "bsl" that is not in the export set.
CMake Error: install(EXPORT "mylibraryInterfaceTargets" ...) includes target "mylibrary-uor-PRIVATE" which requires target "bsl" that is not in the export set.
```
After the fix, everything works as expected:
```
1> Working directory: C:\Users\Eric\CMakeBuilds\ada0bda6-c251-5139-8f08-e9c1da6e6736\build\x86-Release
1> -- Configuring done
1> -- Generating done
...
1> -- Resolving EXTERNAL dependencies: bsl.
1> -- =========================================
1> -- =====            SUMMARY            =====
1> -- =========================================
1> --  RefRoot..........: C:/Workspaces/vcpkg/installed/x86-windows-static
1> --  BuildType........: Release
1> --  UFID.............: opt_mt_exc
1> --  Canonical UFID...: opt_exc_mt
1> --  Install UFID.....: opt_exc_mt
1> --  Install lib path.: lib
1> -- =========================================
1> -- Configuring done
1> -- Generating done
```

### CODE REVIEW

**Comment by EricHripko** [comment]
Can this be merged? @mversche @osubboo

**Comment by mversche** [comment]
I think so. 

@osubboo is primarily responsible for the (not entirely complete) CMake work, I've sent a reminder to him to review this when he's back from vacation next week.

**Comment by EricHripko** [comment]
Awesome! I'll stand by for Oleg.

**Comment by osubboo** [comment]
Finally. We are updating bde libraries and tools to the latest version. I'll incorporate this fix as part of 
initial promotion.

**Pull request closed without merging**
