### PR TITLE
Arm support

### PR DESCRIPTION
**Pull request by adambde**
This should addresss GitHub issue 152.  It is tested, and works with g++ 4.8.2 (Ubuntu/Linaro 4.8.2-19ubuntu1) and clang++ 3.4 (3.4-1ubuntu3).  Clang support does require, however, a separate patch to the bde library itself (for bsls_platform.h).

This allows for native building on Ubuntu-like ARM systems.  (Tested with both an HP Chromebook 11", and a heavily modified Motorola Atrix/WebDock.)

### CODE REVIEW

**Comment by RMGiroux** [comment]
This is being tracked along with other ARM issues in internal ticket #60629091

**Comment by FedeGC87** [comment]
Hello, I'm trying to build bde library for arm and I'm having some troubles. 
I'm not sure if I'm doing it right, could you give an example of waf config and environment variables setting for armv7 bde build?

**Comment by gstrauss** [comment]
@adambde, your pull request specialized -m32 and -m64 to x86_64.  Please add -m32 -m64 for gcc on Solaris, and -maix32 -maix64 for gcc on AIX

unix-SunOS-*-*-gcc
unix-AIX-*-*-gcc

**Comment by gstrauss** [comment]
unix-SunOS-\*-\*-gcc
unix-AIX-\*-\*-gcc

**Comment by gstrauss** [comment]
rebased to resolve merge conflicts, and also addressed my comment above:
https://github.com/gstrauss/bde-tools arm-support 61601f5c1dc168f9a40b9aa77f047f1b5c715a43

**Pull request merged**
